name: gopenqa

on: push

jobs:
  gopenqa:
    name: gopenqa test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Install requirements
        run: go get github.com/streadway/amqp
      - name: Run test suite
        run: go test ./...
